//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.19 at 05:19:26 ÏÂÎç CST 
//


package name.chenyuelin.person.springws.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the name.chenyuelin.person.springws.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindPersonRequest_QNAME = new QName("http://www.cyl.org/person/schemas/", "findPersonRequest");
    private final static QName _FindPersonResponse_QNAME = new QName("http://www.cyl.org/person/schemas/", "findPersonResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: name.chenyuelin.person.springws.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonCommand }
     * 
     */
    public PersonCommand createPersonCommand() {
        return new PersonCommand();
    }

    /**
     * Create an instance of {@link PersonDto }
     * 
     */
    public PersonDto createPersonDto() {
        return new PersonDto();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonCommand }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cyl.org/person/schemas/", name = "findPersonRequest")
    public JAXBElement<PersonCommand> createFindPersonRequest(PersonCommand value) {
        return new JAXBElement<PersonCommand>(_FindPersonRequest_QNAME, PersonCommand.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonDto }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.cyl.org/person/schemas/", name = "findPersonResponse")
    public JAXBElement<PersonDto> createFindPersonResponse(PersonDto value) {
        return new JAXBElement<PersonDto>(_FindPersonResponse_QNAME, PersonDto.class, null, value);
    }

}
