//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.19 at 05:19:26 обнГ CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cyl.org/person/schemas/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package name.chenyuelin.person.springws.dto;
